proxystore/taps

- .pre-commit-config.yaml
- pyproject.toml
- testing/globus.py
- tests/executor/dask_test.py
- tests/executor/parsl_test.py
- webs/executor/__init__.py
- webs/executor/dask.py
- webs/executor/parsl.py
- webs/run/main.py
This only partial addresses #19. TaskVine support is waiting on resolving some issues in the TaskVine executor.
> Add Dask and Parsl support

- pyproject.toml
- webs/wf/__init__.py
- webs/wf/montage/__init__.py
- webs/wf/montage/config.py
- webs/wf/montage/workflow.py
Implemented the Montage workflow to use the framework
- Fixes #13 
`python -m webs.run montage --img-folder ${PWD}/Kimages --img-tbl Kimages.tbl --img-hdr Kimages.hdr --output-dir Kprojdir --executor process-pool --max-processes 10`
> Added Montage workflow

- .pre-commit-config.yaml
- pyproject.toml
- tests/executor/ray_test.py
- tox.ini
- webs/executor/__init__.py
- webs/executor/dask.py
- webs/executor/ray.py
> Add the `RayExecutor`

- tests/wf/synthetic/workflow_test.py
- webs/wf/synthetic/__init__.py
- webs/wf/synthetic/config.py
- webs/wf/synthetic/workflow.py
Expand synthetic workflow.
- Fixes #18
N/A
> Expand synthetic workflow

- .gitignore
- pyproject.toml
- testing/fixtures.py
- tests/data/config_test.py
- tests/data/file_test.py
- tests/data/proxy_test.py
- tests/data/transform_test.py
- tests/executor/workflow_test.py
- tests/wf/synthetic/workflow_test.py
- webs/data/__init__.py
- webs/data/config.py
- webs/data/file.py
- webs/data/null.py
- webs/data/proxy.py
- webs/data/transform.py
- webs/executor/config.py
- webs/executor/workflow.py
- webs/run/config.py
- webs/run/main.py
- webs/wf/synthetic/workflow.py
Add data transformers to CLI.
- Fixes #20
Tested CLI and added some not very comprehensive tests.
> Add data transformers to CLI

- tests/executor/workflow_test.py
- webs/executor/workflow.py
Switching the task wrapper to a decorator broke serializing the task with pickle so process pool stopped working. Oops.
> Partially revert changes in #48

- webs/wf/montage/__init__.py
- webs/wf/montage/workflow.py
Workflow missed a small step of generating a new coadded FITS file for all the images. Added that step.
N/A
> Add missing step in workflow

- pyproject.toml
- tests/data/proxy_test.py
- tests/executor/globus_test.py
- tests/wf/synthetic/workflow_test.py
- webs/data/proxy.py
- webs/executor/dask.py
- webs/executor/globus.py
- webs/executor/python.py
- webs/executor/workflow.py
- webs/run/config.py
- webs/wf/docking/__init__.py
- webs/wf/docking/config.py
- webs/wf/docking/workflow.py
- webs/wf/moldesign/__init__.py
- webs/wf/moldesign/tasks.py
- webs/wf/montage/workflow.py
- webs/wf/synthetic/config.py
- webs/wf/synthetic/workflow.py
See #53
- Fixes #53
Update tests or ran apps where applicable.
> Triage minor errors from paper evaluation

- taps/data/file.py
- taps/data/null.py
- taps/data/proxy.py
- taps/data/transform.py
- taps/engine/engine.py
- taps/engine/transform.py
- taps/run/apps/fedlearn.py
- taps/run/apps/synthetic.py
- taps/run/main.py
- tests/data/file_test.py
- tests/data/null_test.py
- tests/data/proxy_test.py
- tests/engine/transform_test.py
Add `close()` to `DataTransformer`.
Also fixed enum error in some configs.
- Fixes #42
N/A
> Add `close()` to `DataTransformer`

- taps/run/config.py
- taps/run/main.py
- testing/fixtures.py
Add `{executor}` option to run dir.
- Fixes #50
N/A
> Add `{executor}` option to run dir

- README.md
- docs/contributing/releases.md
Update README and release guide
N/A
> Update README and release guide

- .github/release.yml
- .github/workflows/publish.yml
Fix publish workflow and release template.
N/A
> Fix publish workflow and release template

- pyproject.toml
> Bump to TaPS v0.2.0a1

- LICENSE
> Update LICENSE authors

- taps/executor/__init__.py
- taps/executor/globus.py
- taps/executor/python.py
- taps/executor/utils.py
- testing/fixtures.py
- tests/engine/engine_test.py
- tests/executor/python_test.py
- tests/executor/utils_test.py
Rename `DAGExecutor` to `FutureDependencyExecutor`.
- Fixes #76
N/A
> Rename `DAGExecutor` to `FutureDependencyExecutor`

- taps/engine/engine.py
- tests/engine/engine_test.py
Previously, if a task raised an exception, the task callback handler would also raise the exception instead of just recording the exception. This is fixed now, and the execution info in task records is more verbose.
Added a unit test.
> Fix exception logging in task callback

- taps/run/parse.py
- tests/run/parse_test.py
Support multiple config files in CLI with `--config`. Config files are parse in order with options in later files taking precedence over earlier files.
Added test and tested in CLI.
> Support multiple config files in CLI with `--config`

- docs/guides/apps.md
- docs/guides/config.md
- docs/guides/data.md
- docs/guides/executor.md
- docs/guides/index.md
- mkdocs.yml
- taps/executor/dask.py
- taps/executor/globus.py
- taps/executor/parsl.py
- taps/executor/python.py
- taps/executor/ray.py
- taps/transformer/file.py
Add guides for configuration, executors, and data management.
- Fixes #59
N/A
> Add guides for configuration, executors, and data management

- docs/apps/failures.md
- docs/guides/config.md
- pyproject.toml
- taps/run/config.py
- taps/run/env.py
- taps/run/main.py
- taps/run/parse.py
- tests/run/env_test.py
- tests/run/main_test.py
Increase logged information and validate TaPS config versions.
Added tests where needed and validated new logging with test app.
> Increase logged information and validate TaPS config versions

- docs/guides/config.md
- taps/run/config.py
- taps/run/main.py
- taps/run/utils.py
- tests/run/utils_test.py
Support configuring environment variables.
- Fixes #54
Added tests and an example in the config guide which I also tested.
> Support configuring environment variables

- taps/filter/config.py
- taps/filter/filters.py
- tests/engine/engine_test.py
- tests/filter/config_test.py
- tests/filter/filters_test.py
Add `object-type` filter to the CLI and add support for pattern matching against type names.
- Fixes #74
Added new unit tests.
> Add `object-type` filter to the CLI and add support for pattern matching against type names

- docs/guides/index.md
- docs/guides/parsl.md
- mkdocs.yml
- taps/executor/__init__.py
- taps/executor/parsl.py
- tests/executor/parsl_test.py
- tests/run/config_test.py
Improve Parsl configuration extensibility.
- Fixes #79
Added new tests and docs.
> Improve Parsl configuration extensibility

- .pre-commit-config.yaml
- docs/guides/index.md
- docs/guides/scripts.md
- mkdocs.yml
- pyproject.toml
- taps/apps/cholesky.py
- taps/apps/docking/train.py
- taps/apps/fedlearn/app.py
- taps/apps/moldesign/app.py
- taps/apps/moldesign/chemfunctions.py
- taps/executor/parsl.py
- taps/run/config.py
- taps/run/main.py
- taps/run/parse.py
- taps/run/utils.py
- tests/run/config_test.py
- tests/run/utils_test.py
Add guide for custom benchmark scripts. Also made some minor code improvements since this guide will encourage users to use more aspects of the package.
Testing the code examples in the docs.
> Add guide for custom benchmark scripts

- docs/guides/data.md
- pyproject.toml
- taps/transformer/_proxy.py
- tests/transformer/proxy_test.py
Support arbitrary ProxyStore configurations in `ProxyTransformerConfig`. This required upgrading to ProxyStore v0.7.0.
Added tests and tried the docs file connector example.
> Support arbitrary ProxyStore configurations in `ProxyTransformerConfig`

- pyproject.toml
> Bump to TaPS v0.2.0

- pyproject.toml
> Bump to TaPS v0.2.1dev1

- pyproject.toml
- taps/apps/cholesky.py
- taps/apps/configs/cholesky.py
- tests/apps/cholesky_test.py
- tests/apps/configs/cholesky_test.py
Add tests for Cholesky app. Related to #65.
Test pass.
> Add tests for Cholesky app

- pyproject.toml
- taps/apps/mapreduce.py
- tests/apps/configs/mapreduce_test.py
- tests/apps/mapreduce_test.py
Add tests for mapreduce app. Partially fixes #65.
Tests pass.
> Add tests for mapreduce app

- docs/apps/mapreduce.md
> Fix typo in docs mapreduce example

- pyproject.toml
- tests/apps/configs/montage_test.py
- tests/apps/montage_test.py
Add tests for montage app. Note that these tests are heavily mocked, but may help catch incidental regressions.
Related to #65.
Tests pass.
> Add tests for montage app

- pyproject.toml
- taps/apps/configs/fedlearn.py
- tests/apps/configs/docking_test.py
- tests/apps/configs/fedlearn_test.py
- tests/apps/configs/moldesign_test.py
- tests/executor/parsl_test.py
Adds tests for remaining app configs. I've decided that the remaining non-tested apps are too slow to add reasonable tests for.
N/A
> Add tests for remaining app configs

- taps/executor/parsl.py
- tests/executor/parsl_test.py
Add monitoring: Optional[MonitoringConfig]
- Fixes #XX
- Fixes #XX
N/A
> Add monitoring config to Parsl HTEx

- taps/run/config.py
Ensure `run_dir` is an absolute path. 
- Fixes #110
Docking app works now.
> Ensure `run_dir` is an absolute path

- taps/apps/moldesign/app.py
Log failed tasks in moldesign when resubmitting so the user can see when failures are not of the "expected" kind.
N/A
> Log failed tasks in moldesign when resubmitting

- docs/apps/cholesky.md
Fix typo in CLI argument for Cholesky example.
N/A
> Fix typo in CLI argument for Cholesky example

- .github/ISSUE_TEMPLATE/01_bug.yml
- .github/ISSUE_TEMPLATE/02_feature.yml
- .github/ISSUE_TEMPLATE/03_docs.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/pull_request_template.md
- .github/release.yml
- docs/contributing/index.md
- docs/contributing/issues-pull-requests.md
- docs/contributing/style-guide.md
- docs/faq.md
- mkdocs.yml
Add FAQ and update Github templates and contributing guide.
N/A
> Add FAQ and update Github templates and contributing guide

- taps/run/env.py
Record total virtual memory instead of available.
N/A
> Record total virtual memory instead of available

- README.md
- docs/publications/index.md
- mkdocs.yml
Add TaPS preprint citation.
N/A
> Add TaPS preprint citation

- taps/apps/synthetic.py
- tests/engine/engine_test.py
Raise task errors in synthetic bag-of-tasks app.
- Fixes #132
N/A
> Raise task errors in synthetic bag-of-tasks app

- taps/apps/configs/synthetic.py
- taps/apps/synthetic.py
- tests/apps/synthetic_test.py
Support custom number of warmup tasks and fix last batch size in synthetic app.
- Fixes #133 
Ran app.
> Support custom number of warmup tasks and fix last batch size in synthetic app

- taps/run/config.py
- taps/run/main.py
- taps/run/utils.py
- taps/transformer/_proxy.py
- tests/transformer/proxy_test.py
Add `async_resolve` option to `ProxyTransformer` and make `RunConfig.env_vars` optional.
- Fixes #134
Updated unit tests and validated with a real app.
> Add `async_resolve` option to `ProxyTransformer` and make `RunConfig.env_vars` optional

- taps/executor/parsl.py
> Allow multiple Parsl HTEx executors in `ParslHTExConfig`

- docs/apps/docking.md
Update tips for resolving `libsqlite` linking error docking app guide.
- Fixes #151
N/A
> Update tips for resolving `libsqlite` linking error docking app guide

- taps/executor/utils.py
Make child task submission idempotent and thread-safe in `FuturesDependencyExecutor`. This specifically targets `_Task._submit` which used to assert it is only ever called once. It can now be called multiple times, but the submission will only ever be performed by the first thread.
I thought about using locks more liberally in other places to maintain the internal assertion that `_submit()` is only called once, but ultimately I think this solution is easier to reason about.
Related to #145, which addressed some other race conditions.
Not really... I couldn't reliably reproduce the error.
> Make child task submission idempotent and thread-safe in `FuturesDependencyExecutor`

- taps/run/env.py
- taps/run/main.py
- tests/run/env_test.py
Refactor environment collection to make it easier to expand in the future and the environment is now logged to `{run_dir}/environment.json`.
N/A
> Refactor environment collection and log to file

- README.md
- docs/publications/index.md
Update citation with official publication.
N/A
> Update citation with official publication

- pyproject.toml
- tests/executor/ray_test.py
- tox.ini
Extend Ray dependency to Python 3.12 now that wheels are available.
- Fixes #35
N/A
> Extend Ray dependency to Python 3.12

- pyproject.toml
> Bump to TaPS v0.2.1

- pyproject.toml
> Bump to TaPS v0.2.2dev1

- taps/executor/parsl.py
Parsl channels are now fully removed, so we need to remove them as well to maintain compatibility with new versions.
N/A
> Remove all Parsl channels

- docs/apps/index.md
- docs/apps/physics.md
- mkdocs.yml
- pyproject.toml
- taps/apps/configs/physics.py
- taps/apps/physics.py
- taps/engine/_engine.py
- tests/apps/configs/physics_test.py
Add new app `physics` based on [Globus Compute golf demo](https://github.com/globus-labs/globus-compute-golf-demo).
- Fixes #140
Tested the commands in the guide.
> Add physics app based on Globus Compute golf demo

- pyproject.toml
> Bump to TaPS v0.2.2

- pyproject.toml
> Bump to TaPS v0.2.3dev1

- docs/apps/docking.md
Update libsqlite debugging tip in docking app.
- Fixes #151
I tested the solution in the same environment I used to reproduce the original issue.
> Update libsqlite debugging tip in docking app
